# Generated by Django 4.0.4 on 2022-06-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13)),
                ('code', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('text_message', models.TextField()),
                ('date_end', models.DateTimeField(auto_now=True)),
                ('custom', models.ManyToManyField(related_name='Customs', to='Apiapp.custom')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mailing_lists', to='Apiapp.mailing_list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Custom', to='Apiapp.custom')),
            ],
        ),
    ]
